version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/lowtech-gmbh-server
permissions:
  - object: /home/ubuntu/lowtech-gmbh-server
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 60
      runas: ubuntu
