version: '3.1'

services:
  postgresql:
    container_name: lowtech_db
    restart: always
    image: postgres:10.10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres+lowtech+2024
      POSTGRES_DB: lowtech_gmbh
    ports:
      - 0.0.0.0:5432:5432
